!function(t,e,i,s){"use strict"
function n(e,i){this.$element=t(e),this.options=t.extend(!0,{},r,i),this.colHeightArray=[],this.styleQueue=[],this._init()}var o=t(e),a="waterfall",r={itemCls:"waterfall-item",prefix:"waterfall",fitWidth:!0,colWidth:240,gutterWidth:10,gutterHeight:10,align:"center",minCol:1,maxCol:s,maxPage:s,bufferPixel:-50,containerStyle:{position:"relative"},resizable:!0,isFadeIn:!1,isAnimated:!1,animationOptions:{},isAutoPrefill:!0,checkImagesLoaded:!0,path:s,dataType:"json",params:{},headers:{},loadingMsg:'<div style="text-align:center;padding:10px 0; color:#999;"><img src="data:image/gif;base64,R0lGODlhEAALAPQAAP///zMzM+Li4tra2u7u7jk5OTMzM1hYWJubm4CAgMjIyE9PT29vb6KiooODg8vLy1JSUjc3N3Jycuvr6+Dg4Pb29mBgYOPj4/X19cXFxbOzs9XV1fHx8TMzMzMzMzMzMyH5BAkLAAAAIf4aQ3JlYXRlZCB3aXRoIGFqYXhsb2FkLmluZm8AIf8LTkVUU0NBUEUyLjADAQAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27ifDgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeRvsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjothLOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAsAAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00kj5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpyHCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAABS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7" alt=""><br />服务器很小,努力加载,<a href="mailto:aaa@bbb.com?subject=捐赠">捐赠</a>可以使我们做得更好...</div>',state:{isDuringAjax:!1,isProcessingData:!1,isResizing:!1,isPause:!1,curPage:1},callbacks:{loadingStart:function(t){t.show()},loadingFinished:function(t,e){e?t.remove():t.fadeOut()},loadingError:function(t,e){t.html('服务器很小,有时会有错误,<a href="mailto:aaa@bbb.com?subject=捐赠">捐赠</a>可以使我们做得更好...')},renderData:function(e,i){var s,n
return"json"===i||"jsonp"===i?(s=t("#waterfall-tpl").html(),(n=Handlebars.compile(s))(e)):e}},debug:!1}
n.prototype={constructor:n,_debug:function(){!0===this.options.debug&&("undefined"!=typeof console&&"function"==typeof console.log?1===Array.prototype.slice.call(arguments).length&&"string"==typeof Array.prototype.slice.call(arguments)[0]?console.log(""+Array.prototype.slice.call(arguments)):console.log(Array.prototype.slice.call(arguments)):Function.prototype.bind||"undefined"==typeof console||"object"!=typeof console.log||Function.prototype.call.call(console.log,console,Array.prototype.slice.call(arguments)))},_init:function(t){var e=this.options,i=e.path
return this._setColumns(),this._initContainer(),this._resetColumnsHeightArray(),this.reLayout(t),i?(e.isAutoPrefill&&this._prefill(),e.resizable&&this._doResize(),this._doScroll(),s):(this._debug("Invalid path"),s)},_initContainer:function(){var e=this.options,i=e.prefix
t("body").css({overflow:"auto"}),this.$loading&&this.$loading.remove(),this.$message&&this.$message.remove(),this.$element.css(this.options.containerStyle).addClass(i+"-container"),this.$element.after('<div id="'+i+'-loading">'+e.loadingMsg+'</div><div id="'+i+'-message" style="text-align:center;color:#999;"></div>'),this.$loading=t("#"+i+"-loading"),this.$message=t("#"+i+"-message")},_getColumns:function(){var t=this.options,e=t.fitWidth?this.$element.parent():this.$element,i="BODY"===e[0].tagName?e.width()-20:e.width(),s=t.colWidth,n=t.gutterWidth,o=t.minCol,a=t.maxCol,r=Math.floor(i/(s+n)),l=Math.max(r,o)
return a&&l>a?a:l},_setColumns:function(){this.cols=this._getColumns()},_getItems:function(t){var e=t.filter("."+this.options.itemCls).css({position:"absolute"})
return e},_resetColumnsHeightArray:function(){var t,e=this.cols
for(this.colHeightArray.length=e,t=0;e>t;t++)this.colHeightArray[t]=0},layout:function(t,e){var i,s,n,o,a,r,l=this.options,h=this.options.isFadeIn?this._getItems(t).css({opacity:0}).animate({opacity:1}):this._getItems(t),c=this.options.isAnimated&&this.options.state.isResizing?"animate":"css",A=l.animationOptions,u=l.colWidth,g=l.gutterWidth,d=this.colHeightArray.length,p=l.align
for(this.$element.append(h),"center"===p?(i=(this.$element.width()-u*d-g*(d-1))/2,i=i>0?i:0):"left"===p?i=0:"right"===p&&(i=this.$element.width()-u*d-g*(d-1)),n=0,a=h.length;a>n;n++)this._placeItems(h[n],i)
for(o=0,r=this.styleQueue.length;r>o;o++)s=this.styleQueue[o],s.$el[c](s.style,A)
this.$element.height(Math.max.apply({},this.colHeightArray)),this.styleQueue=[],this.options.state.isResizing=!1,this.options.state.isProcessingData=!1,e&&e.call(h)},reLayout:function(t){var e=this.$element.find("."+this.options.itemCls)
this._resetColumnsHeightArray(),this.layout(e,t)},_placeItems:function(e,i){var s,n,o=t(e),a=this.options,r=a.colWidth,l=a.gutterWidth,h=a.gutterHeight,c=this.colHeightArray,A=c.length,u=Math.min.apply({},c),g=t.inArray(u,c)
s=o.hasClass(a.prefix+"-item-fixed-left")?0:o.hasClass(a.prefix+"-item-fixed-right")?A>1?A-1:0:g,n={left:(r+l)*s+i,top:c[s]},this.styleQueue.push({$el:o,style:n}),c[s]+=o.outerHeight()+h},prepend:function(t,e){this.$element.prepend(t),this.reLayout(e)},append:function(t,e){this.$element.append(t),this.reLayout(e)},removeItems:function(t,e){this.$element.find(t).remove(),this.reLayout(e)},option:function(e,i){t.isPlainObject(e)&&(this.options=t.extend(!0,this.options,e),"function"==typeof i&&i(),this._init())},pause:function(t){this.options.state.isPause=!0,"function"==typeof t&&t()},resume:function(t){this.options.state.isPause=!1,"function"==typeof t&&t()},_requestData:function(e){var i,n=this,o=this.options,a=o.maxPage,r=o.state.curPage++,l=o.path,h=o.dataType,c=o.params,A=o.headers
return a!==s&&r>a?(o.state.isBeyondMaxPage=!0,o.callbacks.loadingFinished(this.$loading,o.state.isBeyondMaxPage),s):(i="function"==typeof l?l(r):l.join(r),this._debug("heading into ajax",i+t.param(c)),o.callbacks.loadingStart(this.$loading),o.state.isDuringAjax=!0,o.state.isProcessingData=!0,t.ajax({url:i,data:c,headers:A,dataType:h,success:function(t){n._handleResponse(t,e),n.options.state.isDuringAjax=!1},error:function(t){n._responeseError("error")}}),s)},_handleResponse:function(e,i){if(null==e||0==e.length)return this.$element.empty(),this.$element.html('<div style="text-align:center;color:#999;">没找到...</div>'),this.$loading.remove(),this.$message.remove(),s
var n=this,o=this.options,a=t.trim(o.callbacks.renderData(e,o.dataType)),r=t(a),l=o.checkImagesLoaded
l?r.imagesLoaded(function(){n.append(r,i),n.options.callbacks.loadingFinished(n.$loading,n.options.state.isBeyondMaxPage)}):(n.append(r,i),n.options.callbacks.loadingFinished(n.$loading,n.options.state.isBeyondMaxPage))},_isImgLoaded:function(t,e){var i=0
if(t.each(function(){this.height>0&&i++}),i!=t.length){var s=this
setTimeout(function(){s._isImgLoaded(t,e)},100)}else e()},_responeseError:function(t){this.$loading.hide(),this.options.callbacks.loadingError(this.$message,t),"end"!==t&&"error"!==t&&(t="unknown"),this._debug("Error",t)},_nearbottom:function(){var t=this.options,e=Math.min.apply({},this.colHeightArray),i=o.scrollTop()+o.height()-this.$element.offset().top-e
return this._debug("math:",i),i>t.bufferPixel},_prefill:function(){this.$element.height()<=o.height()&&this._scroll()},_scroll:function(){var t=this.options,e=t.state,i=this
e.isProcessingData||e.isDuringAjax||e.isInvalidPage||e.isPause||this._nearbottom()&&this._requestData(function(){setTimeout(function(){i._scroll()},100)})},_doScroll:function(){var t,e=this
o.bind("scroll",function(){t&&clearTimeout(t),t=setTimeout(function(){e._scroll()},100)})},_resize:function(){var t=this.cols,e=this._getColumns();(e!==t||"left"!==this.options.align)&&(this.options.state.isResizing=!0,this.cols=e,this.reLayout(),this._prefill())},_doResize:function(){var t,e=this
o.bind("resize",function(){t&&clearTimeout(t),t=setTimeout(function(){e._resize()},100)})}},t.fn[a]=function(e){if("string"==typeof e){var i=Array.prototype.slice.call(arguments,1)
this.each(function(){var n=t.data(this,"plugin_"+a)
return n?t.isFunction(n[e])&&"_"!==e.charAt(0)?(n[e].apply(n,i),s):(n._debug('no such method "'+e+'"'),s):(n._debug("instance is not initialization"),s)})}else this.each(function(){t.data(this,"plugin_"+a)||t.data(this,"plugin_"+a,new n(this,e))})
return this}}(jQuery,window,document),function(t,e){"use strict"
var i="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=="
t.fn.imagesLoaded=function(s){function n(){var e=t(u),i=t(g)
l&&(g.length?l.reject(c,e,i):l.resolve(c)),t.isFunction(s)&&s.call(r,c,e,i)}function o(t){a(t.target,"error"===t.type)}function a(e,s){e.src!==i&&-1===t.inArray(e,A)&&(A.push(e),s?g.push(e):u.push(e),t.data(e,"imagesLoaded",{isBroken:s,src:e.src}),h&&l.notifyWith(t(e),[s,c,t(u),t(g)]),c.length===A.length&&(setTimeout(n),c.unbind(".imagesLoaded",o)))}var r=this,l=t.isFunction(t.Deferred)?t.Deferred():0,h=t.isFunction(l.notify),c=r.find("img").add(r.filter("img")),A=[],u=[],g=[]
return t.isPlainObject(s)&&t.each(s,function(t,e){"callback"===t?s=e:l&&l[t](e)}),c.length?c.bind("load.imagesLoaded error.imagesLoaded",o).each(function(s,n){var o=n.src,r=t.data(n,"imagesLoaded")
return r&&r.src===o?(a(n,r.isBroken),e):n.complete&&n.naturalWidth!==e?(a(n,0===n.naturalWidth||0===n.naturalHeight),e):((n.readyState||n.complete)&&(n.src=i,n.src=o),e)}):n(),l?l.promise(r):r}}(jQuery)
